import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Main.module.css";
import Header from "@/components/Header";
import Navigation from "@/components/Navigation.js";
import HomeScreen from "./screens/HomeScreen.js";

export default function Home() {
	return (
		<>
			<Head>
				<title>Prayer Connect Web</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className={styles.main}>
				<Header />
				<Navigation />
				<HomeScreen />
			</main>
		</>
	);
}
