import React, { useEffect } from "react";
import Head from "next/head";
import Image from "next/image";
import { useRouter } from "next/router";
import styles from "@/styles/Main.module.css";
import { Button } from "@mui/material";
import { onAuthStateChanged } from "firebase/auth";
import { auth } from "@/firebase/firebaseApp";
import { userLoggedIn } from "@/redux/slices/userSlice";
import { useDispatch } from "react-redux";

export default function Home() {
	const router = useRouter();
	const dispatch = useDispatch();

	// kick out logged in users who are logged in
	useEffect(() => {
		onAuthStateChanged(auth, (user) => {
			if (user) {
				// Redux store
				dispatch(
					userLoggedIn({
						name: user.displayName,
						email: user.email,
						role: "user",
						uid: user.uid,
					})
				);
			}
			if (user && user.uid) {
				router.push("/home");
			} else {
				console.log("User is null");
			}
		});
		console.log("logged in check pushed you home");
	}, [dispatch, router]);

	return (
		<>
			<Head>
				<title>Prayer Connect Web</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className={styles.main}>
				<Image
					src={"/Illustration.svg"}
					alt={"Globe with two missionaries on a journey to spread the gospel."}
					height={161}
					width={156}
				/>
				<h1 className={styles.h1}>Prayer-Connect</h1>
				<p className={styles.p}>
					This app is designed to help you connect with a diverse community and
					share your prayer requests. Whether you&#39;re looking for support,
					lament, or a space to praise God, this app welcomes all kinds of
					prayers. With features like public and private prayer requests,
					answered prayers, and email notifications, you can customize your
					experience to suit your needs.
				</p>
				<div className={styles.startBtnContainer}>
					<Button href="/login/signup" className={styles.startBtn}>
						Get Started
					</Button>
					<Button href="/login/existing-user" className={styles.loginBtn}>
						Log in
					</Button>
				</div>
				{/* <a href="/home" style={{ color: "red" }}>
					community page
				</a> */}
			</main>
		</>
	);
}
function dispatch(arg0: any) {
	throw new Error("Function not implemented.");
}
