import Head from "next/head";
import styles from "@/styles/Main.module.css";

export default function Home() {
	return (
		<>
			<Head>
				<title>Prayer Connect Web</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className={styles.main}>
				{/* <a href="/community" style={{ color: "red" }}>
					community page
				</a> */}
			</main>
		</>
	);
}
